# Generated by Django 4.1.3 on 2022-11-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='entreprise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='telephone',
            field=models.CharField(default='', max_length=25),
        ),
    ]
