# Generated by Django 4.1.2 on 2022-11-25 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesTaches', '0004_alter_task_due_date_alter_task_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 2, 14, 11, 17, 210143)),
        ),
    ]
